apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileapp
  labels:
    type: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profileapp
  template:
    metadata:
      labels:
        app: profileapp
        type: pod
    spec:
      containers:
      - name: ui-app
        image: afnan39/profile-app:v1.0.31
        ports:
        - containerPort: 8080
          name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
spec:
  type: NodePort
  selector:
    app: profileapp
    type: pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32000
