apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  labels:
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
        type: pod
    spec:
      containers:
      - name: ui-app
        image: image: afnan39/profile-app:v1.0.34
        ports:
        - containerPort: 8080
          name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: ui-app
spec:
  type: NodePort
  selector:
    app: ui-app
    type: pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31000
        
        
